### ISSUE TITLE
Some quetions

### ISSUE THREAD

**Issue by wajeht** [szabacsik/snowflake-json-web-token#1]
If your account is `gg69420.us-east-1.aws.snowflakecomputing.com` what would do put on `account` and `username`? I've been trying every possible combination and it doesn't seem to be working. Any thoughts?

**Comment by szabacsik** [comment]
In that case your account is `gg69420`. The username is not part of the URL. Your username is the one you use to log in to the snowflake console, for example.
I created a simple API test please take a look maybe it helps: <https://github.com/szabacsik/snowflake-json-web-token/blob/1.0.1/tests/EndToEndTest.php>, and I also updated the [readme](https://github.com/szabacsik/snowflake-json-web-token/blob/1.0.1/README.md), how to create private and public keys for snowflake users.

**Comment by wajeht** [comment]
@szabacsik thanks a lot. it works perfectly now!
